name: baseline+smart_init
model: facebook/bart-large

# <--------------
# Linearizations
# Comment DFS and uncomment the relevant block if you want to use a different linearization scheme

# DFS
penman_linearization: True
use_pointer_tokens: True
raw_graph: False

remove_wiki: False
dereify: False
collapse_name_ops: False

# Hparams
batch_size: 500
beam_size: 5
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 45000
grad_norm: 2.5
scheduler: linear
learning_rate: 0.0001
weight_decay: 0.004
adam_eps: 0.00000001
max_epochs: 45
save_checkpoints: True
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024

# <------------------
# Data: replace DATA below with the root of your AMR 2/3 release folder
#train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
#train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
#dev: amr-data-master/amr-2.0/data/amrs/split/dev/*.txt
#test: amr-data-master/amr-2.0/data/amrs/split/test/*.txt
train: amr-data-master/amr-3.0/data/amrs/split/training/*.txt
dev: amr-data-master/amr-3.0/data/amrs/split/dev/*.txt
test: amr-data-master/amr-3.0/data/amrs/split/test/*.txt

align_mode: True
#align_train:  silver/training/*.txt
#align_train:  amr-data-master/amr-2.0/data/alignments/split/training/*.txt
#align_dev: amr-data-master/amr-2.0/data/alignments/split/dev/*.txt
#align_test: amr-data-master/amr-2.0/data/alignments/split/test/*.txt
align_train:  amr-data-master/amr-3.0/data/alignments/split/training/*.txt
align_dev: amr-data-master/amr-3.0/data/alignments/split/dev/*.txt
align_test: amr-data-master/amr-3.0/data/alignments/split/test/*.txt

log_wandb: True
wandb_project: Distillation
calc_smatch: True

double_path: False
keep_full_graph: True
align_from_metadata: False

# Distillation
distil_temp: 1
distil_alpha: 0
copy_decoder: True
copy_encoder: False
smatch_iteration: 130000 # Iteration from which to start calculating SMATCH
aux_mask_task: True
aux_mask_ratio: 0.15

# Encoder Adapter
adapter:
  encoder:
    extra_nodes_as_input: False

    leak_mode: False

    mlp_mode: False
    mlp_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

    graph_mode: False
    graph_type: simple
    graph_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    graph_params:
      pre_transform: True
      residual: True
      dropout: 0.01
