name: baseline+smart_init
model: facebook/bart-large

# <--------------
# Linearizations
# Comment DFS and uncomment the relevant block if you want to use a different linearization scheme

# DFS
penman_linearization: True
use_pointer_tokens: True
raw_graph: False

# BFS
# penman_linearization: False
# use_pointer_tokens: True
# raw_graph: False

# PENMAN
# penman_linearization: True
# use_pointer_tokens: False
# raw_graph: False

# BART baseline
# penman_linearization: True
# use_pointer_tokens: False
# raw_graph: True

remove_wiki: False
dereify: False
collapse_name_ops: False

# Hparams
batch_size: 500
beam_size: 5
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 40000
grad_norm: 2.5
scheduler: linear
learning_rate: 0.00005
weight_decay: 0.004
adam_eps: 0.00000001
max_epochs: 40
save_checkpoints: True
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024

# <------------------
# Data: replace DATA below with the root of your AMR 2/3 release folder
#train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
#dev: amr-data-master/amr-2.0/data/amrs/split/dev/*.txt
#test: amr-data-master/amr-2.0/data/amrs/split/test/*.txt
train: amr-data-master/amr-3.0/data/amrs/split/training/*.txt
dev: amr-data-master/amr-3.0/data/amrs/split/dev/*.txt
test: amr-data-master/amr-3.0/data/amrs/split/test/*.txt


aux_mask_task: True
aux_mask_ratio: 0.15
align_mode: False

log_wandb: True
wandb_project: SPRING
calc_smatch: True
smatch_iteration: 50000 # Iteration from which to start calculating SMATCH

double_path: False

keep_full_graph: False
align_from_metadata: False
clone_mode_for_dp: False

# Encoder Adapter
adapter:
  encoder:
    leak_mode: False

    mlp_mode: False
    mlp_layers: []

    graph_mode: False
    graph_type: simple
    graph_layers: []
    graph_params:
      pre_transform: False
      residual: True
      dropout: 0.01
