name: baseline+smart_init
model: facebook/bart-large

# <--------------
# Linearizations
# Comment DFS and uncomment the relevant block if you want to use a different linearization scheme

# DFS
penman_linearization: True
use_pointer_tokens: True
raw_graph: False

remove_wiki: False
dereify: False
collapse_name_ops: False

# Hparams
batch_size: 500
beam_size: 5
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 40000
grad_norm: 2.5
scheduler: constant
learning_rate: 0.00005
weight_decay: 0.004
adam_eps: 0.00000001
max_epochs: 40
save_checkpoints: True
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024

# <------------------
# Data: replace DATA below with the root of your AMR 2/3 release folder
#train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
dev: amr-data-master/amr-2.0/data/amrs/split/dev/*.txt
test: amr-data-master/amr-2.0/data/amrs/split/test/*.txt

align_mode: True
#align_train:  amr-data-master/amr-2.0/data/alignments/split/training/*.txt
#align_dev: amr-data-master/amr-2.0/data/alignments/split/dev/*.txt
#align_test: amr-data-master/amr-2.0/data/alignments/split/dev/*.txt
align_train:  amr-data-master/amr-3.0/data/alignments/split/training/*.txt
align_dev: amr-data-master/amr-3.0/data/alignments/split/dev/*.txt
align_test: amr-data-master/amr-3.0/data/alignments/split/test/*.txt
#align_train: amr-data-master/leamr-3/alignments/training/*.txt
#align_dev: amr-data-master/leamr-3/alignments/dev/*.txt
#align_test: amr-data-master/leamr-3/alignments/test/*.txt

log_wandb: True
wandb_project: Graph Lekage Model
calc_smatch: True
smatch_iteration: 0 # Iteration from which to start calculating SMATCH

double_path: False
keep_full_graph: False
align_from_metadata: False

aux_mask_task: False
aux_mask_ratio: 0
# Encoder Adapter
adapter:
  encoder:
    extra_nodes_as_input: False

    leak_mode: True

    mlp_mode: False
    mlp_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

    graph_mode: True
    graph_type: simple
    graph_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    graph_params:
      pre_transform: False
      residual: True
      dropout: 0.01
      num_gnn_layers: 1