model: facebook/bart-large

penman_linearization: True
use_pointer_tokens: True
raw_graph: False

remove_wiki: False
dereify: False
collapse_name_ops: False

# Hparams
batch_size: 500
beam_size: 5
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 42000
grad_norm: 2.5
scheduler: linear
learning_rate: 0.00005
weight_decay: 0.004
adam_eps: 0.00000001
max_epochs: 42
save_checkpoints: True
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024

# <------------------
# Data: replace DATA below with the root of your AMR 2/3 release folder

train: amr-data-master/amr-2.0/data/amrs/split/training/*.txt
dev: amr-data-master/amr-2.0/data/amrs/split/dev/*.txt
test: amr-data-master/amr-2.0/data/amrs/split/test/*.txt
#train: amr-data-master/amr-3.0/data/amrs/split/training/*.txt
#dev: amr-data-master/amr-3.0/data/amrs/split/dev/*.txt
#test: amr-data-master/amr-3.0/data/amrs/split/test/*.txt

align_mode: True

# AMR 2
align_train:  amr-data-master/amr-2.0/data/alignments/split/training/*.txt
align_dev: amr-data-master/amr-2.0/data/alignments/split/dev/*.txt
align_test: amr-data-master/amr-2.0/data/alignments/split/test/*.txt

# AMR 3 with ISI alignments
#align_train:  amr-data-master/amr-3.0/data/alignments/split/training/*.txt
#align_dev: amr-data-master/amr-3.0/data/alignments/split/dev/*.txt
#align_test: amr-data-master/amr-3.0/data/alignments/split/test/*.txt

# AMR 3 with LEAMR alignments
#align_train: amr-data-master/leamr-3/alignments/training/*.txt
#align_dev: amr-data-master/leamr-3/alignments/dev/*.txt
#align_test: amr-data-master/leamr-3/alignments/test/*.txt

log_wandb: True
wandb_project: LeakDistill
calc_smatch: True
smatch_iteration: 150000 # Iteration from which to start calculating SMATCH

# Leak Distill parameters
double_path: True # Turn on Leak Distill
beta_sched_steps: 53000
beta_start_value: 90
beta_end_value: 10

kl_multiplier: 20
kl_temperature: 1
exclude_orig_loss: False

keep_full_graph: True # FWAG mode
extra_nodes_mask_prob: 0.0
extra_nodes_contract_prob: 0.0
align_from_metadata: False

clone_mode_for_dp: False

fix_decoder_layers: []

aux_mask_task: True
aux_mask_ratio: 0.15

# Encoder Adapter
adapter:
  encoder:
    extra_nodes_as_input: False

    leak_mode: False

    mlp_mode: False
    mlp_layers: []

    graph_mode: False
    graph_type: simple
    graph_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    graph_params:
      pre_transform: False
      residual: True
      dropout: 0.01
      num_gnn_layers: 1